Repository YeoDamHuman/Travel_Back, pull requests merged in 2025-06, with the labels that each got.

#25 ♻️ REFACTOR : 쓸데없는 코드 삭제 및 코드 리팩터링
  Back-end/src/main/java/com/example/backend/user/controller/UserController.java
  Back-end/src/main/java/com/example/backend/user/service/UserService.java
Labels: ♻️ [REFACTOR], 😨 현빈

#29 ✨ FEAT : CART API 작성
  Back-end/build.gradle
  Back-end/src/main/java/com/example/backend/Swagger UI 이용 가이드.md
  Back-end/src/main/java/com/example/backend/cart/controller/CartController.java
  Back-end/src/main/java/com/example/backend/cart/controller/controller.txt
  Back-end/src/main/java/com/example/backend/cart/dto/dto.txt
  Back-end/src/main/java/com/example/backend/cart/dto/request/CartRequest.java
  Back-end/src/main/java/com/example/backend/cart/dto/response/CartResponse.java
  Back-end/src/main/java/com/example/backend/cart/repository/CartRepository.java
  Back-end/src/main/java/com/example/backend/cart/repository/repository.txt
  Back-end/src/main/java/com/example/backend/cart/service/CartService.java
  Back-end/src/main/java/com/example/backend/cart/service/service.txt
  Back-end/src/main/java/com/example/backend/common/config/RedisConfig.java
  Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
  Back-end/src/main/java/com/example/backend/common/config/SwaggerConfig.java
  Back-end/src/main/java/com/example/backend/common/config/WebClientConfig.java
  Back-end/src/main/java/com/example/backend/health/JpaTestController.java
  Back-end/src/main/java/com/example/backend/health/TourApiTestController.java
  Back-end/src/main/java/com/example/backend/tour/entity/Tour.java
  Back-end/src/main/java/com/example/backend/tour/repository/TourRepository.java
  Back-end/src/main/java/com/example/backend/tour/repository/repository.txt
  Back-end/src/main/java/com/example/backend/tour/webclient/TourApiClient.java
  Back-end/src/main/java/com/example/backend/user/dto/request/UserRequest.java
  Back-end/src/main/java/com/example/backend/user/service/UserService.java
Labels: ✨ [FEAT], 🐛 [FIX], 📝 [DOCS], ♻️ [REFACTOR], 😎 경한

#32 ✨, ♻️ FEAT, REFACTOR : 그룹 생성 기능 구현 및 로그인 로직 필터랑 현재 유저 알아오는거 각각 클래스로 분리
  Back-end/src/main/java/com/example/backend/common/auth/AuthUtil.java
  Back-end/src/main/java/com/example/backend/group/controller/GroupController.java
  Back-end/src/main/java/com/example/backend/group/dto/request/GroupRequest.java
  Back-end/src/main/java/com/example/backend/group/dto/response/GroupResponse.java
  Back-end/src/main/java/com/example/backend/group/entity/Group.java
  Back-end/src/main/java/com/example/backend/group/service/GroupService.java
  Back-end/src/main/java/com/example/backend/user/filter/UserFilter.java
  Back-end/src/main/java/com/example/backend/user/service/UserService.java
Labels: ✨ [FEAT], ♻️ [REFACTOR], 😨 현빈

#34 ✨ FEAT : 그룹 기능 개발
  Back-end/src/main/java/com/example/backend/group/controller/GroupController.java
  Back-end/src/main/java/com/example/backend/group/dto/response/GroupResponse.java
  Back-end/src/main/java/com/example/backend/group/repository/GroupRepository.java
  Back-end/src/main/java/com/example/backend/group/service/GroupService.java
Labels: ✨ [FEAT], 😨 현빈

#35 ♻️ REFACTOR : 유저 회원가입 로직 변경
  Back-end/src/main/java/com/example/backend/user/service/UserService.java
Labels: ♻️ [REFACTOR], 😨 현빈

#38 Develop
  Back-end/src/main/java/com/example/backend/common/config/SwaggerConfig.java
  Back-end/src/main/java/com/example/backend/mail/service/MailService.java
Labels: 🐛 [FIX], ♻️ [REFACTOR], 😨 현빈

#39 🐛 FIX : 회원가입 내 중복검사 오류 수정
  Back-end/src/main/java/com/example/backend/common/config/SwaggerConfig.java
  Back-end/src/main/java/com/example/backend/user/service/UserService.java
Labels: ♻️ [REFACTOR], 😨 현빈
