Repository YeoDamHuman/Travel_Back, pull requests merged in 2025-07, with the labels that each got.

#41 ✨ FEAT: 날씨 API 연동 및 조회 기능 구현
  Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
  Back-end/src/main/java/com/example/backend/weather/controller/WeatherController.java
  Back-end/src/main/java/com/example/backend/weather/dto/response/WeatherResponse.java
  Back-end/src/main/java/com/example/backend/weather/service/WeatherService.java
Labels: ✨ [FEAT], 😨 현빈

#44 ✨ FEAT: 게시판, 댓글 API 개발
  Back-end/src/main/java/com/example/backend/board/controller/BoardController.java
  Back-end/src/main/java/com/example/backend/board/dto/request/BoardRequestDto.java
  Back-end/src/main/java/com/example/backend/board/dto/request/BoardUpdateRequestDto.java
  Back-end/src/main/java/com/example/backend/board/dto/response/BoardDetailResponseDto.java
  Back-end/src/main/java/com/example/backend/board/dto/response/BoardListResponseDto.java
  Back-end/src/main/java/com/example/backend/board/entity/Board.java
  Back-end/src/main/java/com/example/backend/board/repository/BoardRepository.java
  Back-end/src/main/java/com/example/backend/board/service/BoardService.java
  Back-end/src/main/java/com/example/backend/comment/controller/CommentController.java
  Back-end/src/main/java/com/example/backend/comment/dto/request/CommentRequestDto.java
  Back-end/src/main/java/com/example/backend/comment/dto/request/CommentUpdateRequestDto.java
  Back-end/src/main/java/com/example/backend/comment/dto/response/CommentPagingResponseDto.java
  Back-end/src/main/java/com/example/backend/comment/dto/response/CommentResponseDto.java
  Back-end/src/main/java/com/example/backend/comment/entity/Comment.java
  Back-end/src/main/java/com/example/backend/comment/repository/CommentRepository.java
  Back-end/src/main/java/com/example/backend/comment/service/CommentService.java
  Back-end/src/main/java/com/example/backend/common/config/SecurityConfig.java
  Back-end/src/main/java/com/example/backend/tour/entity/Tour.java
Labels: ✨ [FEAT], 🤯 재균

#46 ♻️ REFACTOR : 원본으로 복구
  Back-end/TourAPI_Manual.md
  Back-end/src/main/java/com/example/backend/admin/controller/AdminController.java
  Back-end/src/main/java/com/example/backend/admin/dto/request/AdminRequest.java
  Back-end/src/main/java/com/example/backend/admin/dto/response/AdminResponse.java
  Back-end/src/main/java/com/example/backend/admin/filter/AdminFilter.java
  Back-end/src/main/java/com/example/backend/admin/service/AdminService.java
  Back-end/src/main/java/com/example/backend/board/repository/BoardRepository.java
  Back-end/src/main/java/com/example/backend/comment/repository/CommentRepository.java
  Back-end/src/main/java/com/example/backend/user/entity/User.java
  Back-end/한국관광공사_TourAPI활용매뉴얼(국문)_v4.3.docx
  untitled/.gitignore
  untitled/.idea/.gitignore
  untitled/.idea/.name
  untitled/.idea/description.html
  untitled/.idea/gradle.xml
  untitled/.idea/misc.xml
  untitled/.idea/project-template.xml
  untitled/.idea/template-meta.xml
  untitled/.idea/vcs.xml
  untitled/build.gradle
  untitled/gradle/wrapper/gradle-wrapper.jar
  untitled/gradle/wrapper/gradle-wrapper.properties
  untitled/gradlew
  untitled/gradlew.bat
  untitled/settings.gradle
  untitled/src/main/java/org/scoula/config/RootConfig.java
  untitled/src/main/java/org/scoula/config/ServletConfig.java
  untitled/src/main/java/org/scoula/config/WebConfig.java
  untitled/src/main/java/org/scoula/controller/HomeController.java
  untitled/src/main/java/org/scoula/ex01/HelloServlet.java
  untitled/src/main/resources/log4j2.xml
  untitled/src/main/webapp/WEB-INF/views/index.jsp
Labels: ♻️ [REFACTOR], 😨 현빈
